name: nfc_in_flutter
description: Flutter plugin to read and write NFC tags on both Android and iOS. Currently it only supports reading NDEF formatted tags.
version: 3.0.0
homepage: https://github.com/semlette/nfc_in_flutter
repository: https://github.com/semlette/nfc_in_flutter

environment:
    sdk: ">=2.16.1 <3.0.0"
  

dependencies:
    flutter:
        sdk: flutter

dev_dependencies:
    flutter_test:
        sdk: flutter

flutter:
    plugin:
        platforms:
            android:
                package: dev.semler.nfc_in_flutter
                pluginClass: NfcInFlutterPlugin
            ios:
                pluginClass: NfcInFlutterPlugin
